name: Build PyTorch Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        pytorch-version: [2.3.0, 2.4.0, 2.5.0]
        cuda-version: [12.1, 12.4]
    env:
      CIBW_SKIP: cp36-*
      CIBW_MANYLINUX_X86_64_IMAGE: "nvidia/cuda:${{ matrix.cuda-version }}-devel-ubuntu20.04"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.pytorch-version }}+cu${{ matrix.cuda-version }} torchvision==${{ matrix.pytorch-version }}+cu${{ matrix.cuda-version }} --extra-index-url https://download.pytorch.org/whl/cu${{ matrix.cuda-version }}
        pip install cmake
        pip install cibuildwheel

    - name: Build wheels
      run: |
        cibuildwheel --platform linux
        mkdir -p dist
        cp wheelhouse/*.whl dist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/
